### ISSUE TITLE
Add Makefile and/or README.md

### ISSUE THREAD

**Issue by no-boot-device** [nullifiedcat/cathook-ipc-server#1]
...but seriously, how the fuck do you build this?

**Comment by nullifiedcat** [comment]
Sorry. This is an eclipse project I've uploaded to github. I will make a makefile today/tomorrow

**Comment by no-boot-device** [comment]
Here's what I used to build this based on the Eclipse project file (I don't have Eclipse so I... made do.)
`g++ src/main.cpp -I./simple-ipc/src/include/ -std=gnu++14 -lpthread -lrt  -fmessage-length=0 -m32 -include simple-ipc/src/include/cmp.cpp -include simple-ipc/src/include/util.cpp`

**Comment by nullifiedcat** [comment]
Fixed in d834ea46a93a23f9c9ea100719b181bb4db75a1a
